#include "vehicles.hpp"
#include "../gta/joaat.hpp"

using namespace extremum::menu::info_structs;

#pragma warning(push)
#pragma warning(disable : 26812)
namespace extremum::menu {
	namespace massives {
		vehicles_array::vehicles_array()
		{
			g_vehicles = this;
		}
		vehicles_array::~vehicles_array()
		{
			g_vehicles = nullptr;
		}

		const vehicles_array::vehicle_array_by_name_t& vehicles_array::get_sorted_by_name() const
		{
			return m_vehicles.get<vehicle_info::ByName>();
		}
		const vehicles_array::vehicle_array_by_dlc_t& vehicles_array::get_sorted_by_dlc() const
		{
			return m_vehicles.get<vehicle_info::ByDLC>();
		}
		const vehicles_array::vehicle_array_by_class_t& vehicles_array::get_sorted_by_class() const
		{
			return m_vehicles.get<vehicle_info::ByClass>();
		}

		const vehicles_array::vehicle_array_t vehicles_array::m_vehicles{
			{ RAGE_JOAAT_IMPL("blista"), "blista", "Dinka Blista", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("brioso"), "brioso", "Grotti Brioso R/A", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dilettante"), "dilettante", "Karin Dilettante", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dilettante2"), "dilettante2", "Karin Dilettante (Patrol)", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("issi2"), "issi2", "Wenny Issi", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("issi3"), "issi3", "Wenny Issi (Arena)", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("issi4"), "issi4", "Wenny Issi Classic", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("issi5"), "issi5", "Wenny Issi", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("issi6"), "issi6", "Wenny Issi", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("panto"), "panto", "Benefactor Panto", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("prairie"), "prairie", "Bollokan Prairie", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rhapsody"), "rhapsody", "Declasse Rhapsody", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("club"), "club", "BF Club", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("brioso2"), "brioso2", "Brioso 300", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("weevil"), "weevil", "Weevil", VEHICLE_CLASS_COMPACT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("asea"), "asea", "Declasse Asea", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("asea2"), "asea2", "Declasse Asea", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("asterope"), "asterope", "Karin Asterope", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cog55"), "cog55", "Enus Cognoscenti 55", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cog552"), "cog552", "Enus Cognoscenti 55 (Armored)", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cognoscenti"), "cognoscenti", "Enus Cognoscenti", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cognoscenti2"), "cognoscenti2", "Enus Cognoscenti (Armored)", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("emperor"), "emperor", "Albany Emperor", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("emperor2"), "emperor2", "Albany Emperor", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("emperor3"), "emperor3", "Albany Emperor", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("fugitive"), "fugitive", "Cheval Fugitive", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("glendale"), "glendale", "Benefactor Glendale", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ingot"), "ingot", "Vulcar Ingot", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("intruder"), "intruder", "Karin Intruder", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("limo2"), "limo2", "Benefactor Turreted Limo", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("premier"), "premier", "Declasse Premier", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("primo"), "primo", "Albany Primo", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("primo2"), "primo2", "Albany Primo Custom", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("regina"), "regina", "Dundreary Regina", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("schafter2"), "schafter2", "Benefactor Schafter", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("schafter5"), "schafter5", "Benefactor Schafter LWB", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("schafter6"), "schafter6", "Benefactor Schafter V12 (Armored)", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("stafford"), "stafford", "Enus Stafford", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("stanier"), "stanier", "Vapid Stanier", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("stratum"), "stratum", "Zirconium Stratum", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("superd"), "superd", "Enus Super Diamond", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("surge"), "surge", "Cheval Surge", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tailgater"), "tailgater", "Obey Tailgater", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("warrener"), "warrener", "Vulcar Warrener", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("washington"), "washington", "Albany Washington", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("glendale2"), "glendale2", "Benefactor Glendale Custom", VEHICLE_CLASS_SEDAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("baller"), "baller", "Gallivanter Baller", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("baller2"), "baller2", "Gallivanter Baller II", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("baller3"), "baller3", "Gallivanter Baller LE", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("baller4"), "baller4", "Gallivanter Baller LE (Armored)", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("baller5"), "baller5", "Gallivanter Baller LE LWB", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("baller6"), "baller6", "Gallivanter Baller LE LWB (Armored)", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bjxl"), "bjxl", "Karin BeeJay XL", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cavalcade"), "cavalcade", "Albany Cavalcade", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cavalcade2"), "cavalcade2", "Albany Cavalcade II", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("contender"), "contender", "Vapid Contender", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dubsta"), "dubsta", "Benefactor Dubsta", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dubsta2"), "dubsta2", "Benefactor Dubsta 6x6", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("fq2"), "fq2", "Fathom FQ 2", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("granger"), "granger", "Declasse Granger", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("gresley"), "gresley", "Bravado Gresley", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("habanero"), "habanero", "Emperor Habanero", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("mesa"), "mesa", "Canis Mesa", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("mesa2"), "mesa2", "Canis Mesa", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("novak"), "novak", "Novak", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("patriot"), "patriot", "Mammoth Patriot", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("patriot2"), "patriot2", "Mammoth Patriot Stretch", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("radi"), "radi", "Vapid Radius", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rocoto"), "rocoto", "Obey Rocoto", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("seminole"), "seminole", "Canis Seminole", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("serrano"), "serrano", "Benefactor Serrano", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("toros"), "toros", "Pegassi Toros", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("xls"), "xls", "Benefactor XLS", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("xls2"), "xls2", "Benefactor XLS (Armored)", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("seminole2"), "seminole2", "Canis Seminole Frontier", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("landstalker2"), "landstalker2", "Dundreary Landstalker XL", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("squaddie"), "squaddie", "Mammoth Squaddie", VEHICLE_CLASS_SUV, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cogcabrio"), "cogcabrio", "Enus Cognoscenti Cabrio", VEHICLE_CLASS_COUPES, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("f620"), "f620", "Ocelot F620", VEHICLE_CLASS_COUPES, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("felon"), "felon", "Lampadati Felon", VEHICLE_CLASS_COUPES, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("felon2"), "felon2", "Lampadati Felon GT", VEHICLE_CLASS_COUPES, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("jackal"), "jackal", "Ocelot Jackal", VEHICLE_CLASS_COUPES, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("oracle"), "oracle", "Ubermacht Oracle", VEHICLE_CLASS_COUPES, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("oracle2"), "oracle2", "Ubermacht Oracle XS", VEHICLE_CLASS_COUPES, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sentinel"), "sentinel", "Ubermacht Sentinel", VEHICLE_CLASS_COUPES, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sentinel2"), "sentinel2", "Ubermacht Sentinel XS", VEHICLE_CLASS_COUPES, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("windsor"), "windsor", "Enus Windsor", VEHICLE_CLASS_COUPES, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("windsor2"), "windsor2", "Enus Windsor Drop", VEHICLE_CLASS_COUPES, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("zion"), "zion", "Ubermacht Zion", VEHICLE_CLASS_COUPES, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("zion2"), "zion2", "Ubermacht Zion Cabrio", VEHICLE_CLASS_COUPES, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("blade"), "blade", "Vapid Blade", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("buccaneer"), "buccaneer", "Albany Buccaneer", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("buccaneer2"), "buccaneer2", "Albany Buccaneer Custom", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("chino"), "chino", "Vapid Chino", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("chino2"), "chino2", "Vapid Chino Custom", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("clique"), "clique", "Vapid Clique", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("coquette3"), "coquette3", "Invetero Coquette BlackFin", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("deviant"), "deviant", "Schyster Deviant", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dominator"), "dominator", "Vapid Dominator", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dominator2"), "dominator2", "Vapid Dominator", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dominator3"), "dominator3", "Vapid Dominator GTX", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dominator4"), "dominator4", "Vapid Dominator (Arena)", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dominator5"), "dominator5", "Vapid Dominator (Arena)", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dominator6"), "dominator6", "Vapid Dominator (Arena)", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dukes"), "dukes", "Imponte Dukes", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dukes2"), "dukes2", "Imponte Duke O'Death", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("faction"), "faction", "Willard Faction", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("faction2"), "faction2", "Willard Faction Custom", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("faction3"), "faction3", "Willard Faction Custom Donk", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("gauntlet"), "gauntlet", "Bravado Gauntlet", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("gauntlet2"), "gauntlet2", "Bravado Gauntlet", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("gauntlet3"), "gauntlet3", "Bravado Gauntlet Classic", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("gauntlet4"), "gauntlet4", "Bravado Gauntlet Hellfire", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("hermes"), "hermes", "Albany Hermes", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("hotknife"), "hotknife", "Vapid Hotknife", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("impaler"), "impaler", "Declasse Impaler", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("impaler2"), "impaler2", "Declasse Impaler (Arena)", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("impaler3"), "impaler3", "Declasse Impaler", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("impaler4"), "impaler4", "Declasse Impaler (Arena)", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("imperator"), "imperator", "Vapid Imperator (Arena)", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("imperator2"), "imperator2", "Vapid Imperator (Arena)", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("imperator3"), "imperator3", "Vapid Imperator (Arena)", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("lurcher"), "lurcher", "Albany Lurcher", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("moonbeam"), "moonbeam", "Declasse Moonbeam", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("moonbeam2"), "moonbeam2", "Declasse Moonbeam Custom", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("nightshade"), "nightshade", "Imponte Nightshade", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("peyote2"), "peyote2", "Peyote Gasser", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("phoenix"), "phoenix", "Imponte Phoenix", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("picador"), "picador", "Cheval Picador", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ratloader"), "ratloader", "Bravado Rat-Loader", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ratloader2"), "ratloader2", "Bravado Rat-Truck", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ruiner"), "ruiner", "Imponte Ruiner", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ruiner2"), "ruiner2", "Imponte Ruiner 2000", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ruiner3"), "ruiner3", "Imponte Ruiner", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sabregt"), "sabregt", "Declasse Sabre Turbo", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sabregt2"), "sabregt2", "Declasse Sabre Turbo Custom", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("slamvan"), "slamvan", "Vapid Slamvan Custom", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("slamvan2"), "slamvan2", "Vapid Slamvan Custom", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("slamvan3"), "slamvan3", "Vapid Slamvan", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("slamvan4"), "slamvan4", "Vapid Slamvan (Arena)", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("slamvan5"), "slamvan5", "Vapid Slamvan (Arena)", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("slamvan6"), "slamvan6", "Vapid Slamvan (Arena)", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("stalion"), "stalion", "Declasse Stallion", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("stalion2"), "stalion2", "Declasse Stallion", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tampa"), "tampa", "Declasse Tampa", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tampa3"), "tampa3", "Declasse Tampa", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tulip"), "tulip", "Declasse Tulip", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("vamos"), "vamos", "Declasse Vamos", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("vigero"), "vigero", "Declasse Vigero", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("virgo"), "virgo", "Albany Vigro", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("virgo2"), "virgo2", "Dundreary Vigro Classic", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("virgo3"), "virgo3", "Dundreary Vigro Classic Custom", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("voodoo"), "voodoo", "Declasse Voodoo", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("voodoo2"), "voodoo2", "Declasse Voodoo Custom", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("yosemite"), "yosemite", "Declasse Yosemite", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("gauntlet5"), "gauntlet5", "Bravado Gauntlet Classic Custom", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("manana2"), "manana2", "Albany Manana Custom", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dukes3"), "dukes3", "Imponte Beater Dukes", VEHICLE_CLASS_MUSCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ardent"), "ardent", "Ocelot Ardent", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("btype"), "btype", "Albany Franken Stange", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("btype2"), "btype2", "Albany Franken Stange", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("btype3"), "btype3", "Albany Franken Stange", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("casco"), "casco", "Lampadati Casco", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cheetah2"), "cheetah2", "Grotti Cheetah Classic", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("coquette2"), "coquette2", "Invetero Coquette Classic (Topless)", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("deluxo"), "deluxo", "Imponte Deluxo", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dynasty"), "dynasty", "Weeny Dynasty", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("feltzer3"), "feltzer3", "Benefactor Stirling GT", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("gt500"), "gt500", "Grotti GT500", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("infernus2"), "infernus2", "Pegassi Infernus Classic", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("jb700"), "jb700", "Dewbauchee JB 700", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("mamba"), "mamba", "Declasse Mamba", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("manana"), "manana", "Albany Manana", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("monroe"), "monroe", "Pegassi Monroe", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("nebula"), "nebula", "Vulcar Nebula Turbo", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("peyote"), "peyote", "Vapid Peyote", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("pigalle"), "pigalle", "Lampadati Pigalle", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rapidgt3"), "rapidgt3", "Dewbauchee Rapid GT Classic", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("retinue"), "retinue", "Vapid Retinue", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("savestra"), "savestra", "Annis Savestra", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("stinger"), "stinger", "Grotti Stinger", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("stingergt"), "stingergt", "Grotti Stinger (Topless)", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("stromberg"), "stromberg", "Ocelot Stromberg", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("swinger"), "swinger", "Ocelot Swinger", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("torero"), "torero", "Pegassi Torero", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tornado"), "tornado", "Declasse Tornado", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tornado2"), "tornado2", "Declasse Tornado (Gang)", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tornado3"), "tornado3", "Declasse Tornado Convertible", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tornado4"), "tornado4", "Declasse Tornado Convertible (Gang)", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tornado5"), "tornado5", "Declasse Tornado Custom", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tornado6"), "tornado6", "Declasse Tornado Rat Rod", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("turismo2"), "turismo2", "Grotti Turismo Classic", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("viseris"), "viseris", "Lampadati Viseris", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ztype"), "ztype", "Truffade Z-Type", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("zion3"), "zion3", "Ubermacht Zion Classic", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cheburek"), "cheburek", "Cheburek", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("peyote3"), "peyote3", "Vapid Peyote Custom", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("toreador"), "toreador", "Toreador", VEHICLE_CLASS_SPORT_CLASSIC, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("alpha"), "alpha", "Albany Alpha", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("banshee"), "banshee", "Bravado Banshee", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bestiagts"), "bestiagts", "Grotti Bestia GTS", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("blista2"), "blista2", "Dinka Blista Compact", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("blista3"), "blista3", "Dinka Go Go Monkey Blista", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("buffalo"), "buffalo", "Bravado Buffalo", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("buffalo2"), "buffalo2", "Bravado Buffalo S", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("buffalo3"), "buffalo3", "Bravado Sprunk Buffalo", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("carbonizzare"), "carbonizzare", "Grotti Carbonizzare", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("comet2"), "comet2", "Pfister Comet", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("comet3"), "comet3", "Pfister Comet SR", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("comet4"), "comet4", "Pfister Comet Safari", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("coquette"), "coquette", "Invetero Coquette", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("drafter"), "drafter", "Obey 8F Drafter", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dynasty"), "dynasty", "Dynasty", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("deveste"), "deveste", "Principe Deveste Eight", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("elegy"), "elegy", "Annis Elegy RH8", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("elegy2"), "elegy2", "Annis Elegy Retro Custom", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("feltzer2"), "feltzer2", "Benefactor Feltzer", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("furoregt"), "furoregt", "Lampadati Furore GT", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("fusilade"), "fusilade", "Schyster Fusilade", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("futo"), "futo", "Karin Futo", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("hotring"), "hotring", "Declasse Hotring Sabre", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("issi7"), "issi7", "Weeny Issi Sport", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("infernus2"), "infernus2", "Infernus Classic", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("italigto"), "italigto", "Grotti Itali GTO", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("jugular"), "jugular", "Ocelot Jugular", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("jester"), "jester", "Dinka Jester", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("jester2"), "jester2", "Dinka Jester (Racecar)", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("jester3"), "jester3", "Dinka Jester", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("khamelion"), "khamelion", "Hijak Khamelion", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("kuruma"), "kuruma", "Karin Kuruma", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("kuruma2"), "kuruma2", "Karin Kuruma (Armored)", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("locust"), "locust", "Ocelot Locust", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("lynx"), "lynx", "Ocelot Lynx", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("massacro"), "massacro", "Dewbauchee Massacro", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("massacro2"), "massacro2", "Dewbauchee Massacro (Racecar)", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("neo"), "neo", "Vysser Neo", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("neon"), "neon", "Pfister Neon", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ninef"), "ninef", "9F", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ninef2"), "ninef2", "9F Cabrio", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("omnis"), "omnis", "Obey Omnis", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("paragon"), "paragon", "Enus Paragon R", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("paragon2"), "paragon2", "Enus Paragon R (Armored)", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("pariah"), "pariah", "Ocelot Pariah", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("penumbra"), "penumbra", "Maibatsu Penumbra", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("raiden"), "raiden", "Coil Raiden", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rapidgt"), "rapidgt", "Dewbauchee Rapid GT", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rapidgt2"), "rapidgt2", "Dewbauchee Rapid GT Sports", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("raptor"), "raptor", "BF Raptor", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("revolter"), "revolter", "Ubermacht Revolter", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ruston"), "ruston", "Hijak Ruston", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("schafter3"), "schafter3", "Benefactor Schafter LWB", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("schafter4"), "schafter4", "Benefactor Schafter LWB", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("schafter5"), "schafter5", "Benefactor Schafter V12", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("schafter6"), "schafter6", "Benefactor Schafter V12", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("schlagen"), "schlagen", "Benefactor Schlagen GT", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("schwarzer"), "schwarzer", "Benefactor Schwartzer", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sentinel3"), "sentinel3", "Ubermacht Sentinel Classic", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("seven70"), "seven70", "Dewbauchee Seven-70", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("specter"), "specter", "Dewbauchee Specter", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("specter2"), "specter2", "Dewbauchee Specter Custom", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("streiter"), "streiter", "Benefactor Streiter", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sultan"), "sultan", "Karin Sultan", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("surano"), "surano", "Benefactor Surano", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tampa2"), "tampa2", "Declasse Drift Tampa", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tropos"), "tropos", "Lampadati Tropos Rallye", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("verlierer2"), "verlierer2", "Bravado Verlierer", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("zr380"), "zr380", "Annis ZR 380 (Arena)", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("zr3802"), "zr3802", "Annis ZR 380 (Arena)", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("zr3803"), "zr3803", "Annis ZR 380 (Arena)", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("penumbra2"), "penumbra2", "Maibatsu Penumbra FF", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("coquette4"), "coquette4", "Invetero Coquette D10", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("veto"), "veto", "Veto Classic (Go-Kart)", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("veto2"), "veto2", "Veto Modern (Go-Kart)", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("italirsx"), "italirsx", "Grotti Itali RSX", VEHICLE_CLASS_SPORT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("adder"), "adder", "Truffade Adder", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("autarch"), "autarch", "Overflod Autarch", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("banshee2"), "banshee2", "Bravado Banshee 900R", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bullet"), "bullet", "Vapid Bullet", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cheetah"), "cheetah", "Grotti Cheetah", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cyclone"), "cyclone", "Coil Cyclone", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("entityxf"), "entityxf", "Overflod Entity XF", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("emerus"), "emerus", "Progen Emerus", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("fmj"), "fmj", "Vapid FMJ", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("gp1"), "gp1", "Progen GP1", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("infernus"), "infernus", "Pegassi Infernus", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("italigtb"), "italigtb", "Progen Itali GTB", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("italigtb2"), "italigtb2", "Progen Itali GTB Custom", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("krieger"), "krieger", "Benefactor Krieger", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("le7b"), "le7b", "Annis RE-7B", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("nero"), "nero", "Truffade Nero", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("nero2"), "nero2", "Truffade Nero Custom", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("osiris"), "osiris", "Pegassi Osiris", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("penetrator"), "penetrator", "Ocelot Penetrator", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("pfister811"), "pfister811", "Pfister 811", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("prototipo"), "prototipo", "Grotti X80 Proto", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("reaper"), "reaper", "Pegassi Reaper", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("s80"), "s80", "Annis S80RR", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sc1"), "sc1", "Ubermacht SC1", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("scramjet"), "scramjet", "Declasse Scramjet", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sheava"), "sheava", "Emperor ETR1", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sultanrs"), "sultanrs", "Karin Sultan RS", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("t20"), "t20", "Progen T20", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tempesta"), "tempesta", "Pegassi Tempesta", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tezeract"), "tezeract", "Pegassi Tezeract", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("thrax"), "thrax", "Truffade Thrax", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("turismor"), "turismor", "Grotti Turismo R", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tyrus"), "tyrus", "Progen Tyrus", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("vacca"), "vacca", "Pegassi Vacca", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("vagner"), "vagner", "Dewbauchee Vagner", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("vigilante"), "vigilante", "Grotti Vigilante", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("visione"), "visione", "Grotti Visione", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("voltic"), "voltic", "Coil Voltic", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("voltic2"), "voltic2", "Coil Voltic (Topless)", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("xa21"), "xa21", "Ocelot XA-21", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("zentorno"), "zentorno", "Pegassi Zentorno", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("zorrusso"), "zorrusso", "Pegassi Zorrusso", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tigon"), "tigon", "Lampadati Tigon", VEHICLE_CLASS_SUPER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("akuma"), "akuma", "Dinka Akuma", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("avarus"), "avarus", "LCC Avarus", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bagger"), "bagger", "Western Bagger", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bati"), "bati", "Pegassi Bati 801", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bati2"), "bati2", "Pegassi Bati 801RR", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bf400"), "bf400", "Nagasaki BF400", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("carbonrs"), "carbonrs", "Nagasaki Carbon RS", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("chimera"), "chimera", "Nagasaki Chimera", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cliffhanger"), "cliffhanger", "Western Cliffhanger", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("daemon"), "daemon", "Western Daemon", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("daemon2"), "daemon2", "Western Daemon Custom", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("defiler"), "defiler", "Shitzu Defiler", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("deathbike"), "deathbike", "Western Deathbike (Arena)", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("deathbike2"), "deathbike2", "Western Deathbike (Arena)", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("deathbike3"), "deathbike3", "Western Deathbike (Arena)", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("diablous"), "diablous", "Principe Diabolus", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("diablous2"), "diablous2", "Principe Diabolus Custom", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("double"), "double", "Dinka Double-T", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("enduro"), "enduro", "Dinka Enduro", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("esskey"), "esskey", "Pegassi Esskey", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("faggio"), "faggio", "Pegassi Faggio Sport", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("faggio2"), "faggio2", "Pegassi Faggio", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("faggio3"), "faggio3", "Pegassi Faggio Mod", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("fcr"), "fcr", "Pegassi FCR 1000", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("fcr2"), "fcr2", "Pegassi FCR 1000 Custom", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("gargoyle"), "gargoyle", "Western Gargoyle", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("hakuchou"), "hakuchou", "Shitzu Hakuchou", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("hakuchou2"), "hakuchou2", "Shitzu Hakuchou Drag Bike", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("hexer"), "hexer", "LCC Hexer", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("innovation"), "innovation", "LCC Innovation", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("lectro"), "lectro", "Principe Lectro", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("manchez"), "manchez", "Maibatsu Manchez", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("nemesis"), "nemesis", "Principe Nemesis", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("nightblade"), "nightblade", "Western Nightblade", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("oppressor"), "oppressor", "Pegassi Oppressor", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("oppressor2"), "oppressor2", "Pegassi Oppressor MK II", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("pcj"), "pcj", "Shitzu PCJ 600", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ratbike"), "ratbike", "Western Rat bike", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ruffian"), "ruffian", "Pegassi Ruffian", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rrocket"), "rrocket", "Rampant Rocket", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sanchez2"), "sanchez2", "Maibatsu Sanchez", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sanctus"), "sanctus", "LCC Sanctus", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("shotaro"), "shotaro", "Nagasaki Shotaro", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sovereign"), "sovereign", "Western Sovereign", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("thrust"), "thrust", "Dinka Thrust", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("vader"), "vader", "Shitzu Vader", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("vindicator"), "vindicator", "Dinka Vindicator", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("vortex"), "vortex", "Pegassi Vortex", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("wolfsbane"), "wolfsbane", "Western Wolfsbane", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("zombiea"), "zombiea", "Western Zombie Bobber", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("zombieb"), "zombieb", "Western Zombie Chopper", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("manchez2"), "manchez2", "Maibatsu Manchez Scout", VEHICLE_CLASS_MOTORCYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bfinjection"), "bfinjection", "BF Injection", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bifta"), "bifta", "BF Bifta", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("blazer"), "blazer", "Nagasaki Blazer", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("blazer2"), "blazer2", "Nagasaki Blazer Lifeguard", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("blazer3"), "blazer3", "Nagasaki Hot Rod Blazer", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("blazer4"), "blazer4", "Nagasaki Blazer 4", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("blazer5"), "blazer5", "Nagasaki Blazer Aqua", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bodhi2"), "bodhi2", "Canis Bodhi", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("brawler"), "brawler", "Coil Brawler", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bruiser"), "bruiser", "Benefactor Bruiser (Arena)", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bruiser2"), "bruiser2", "Benefactor Bruiser (Arena)", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bruiser3"), "bruiser3", "Benefactor Bruiser (Arena)", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("caracara2"), "caracara2", "Vapid Caracara", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dloader"), "dloader", "Bravado Duneloader", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dubsta3"), "dubsta3", "Benefactor Dubsta 6x6", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dune"), "dune", "BF Dune Buggy", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dune2"), "dune2", "BF Dune Buggy", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dune3"), "dune3", "BF Dune FAV", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dune4"), "dune4", "BF Dune Buggy", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dune5"), "dune5", "BF Dune Buggy", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("freecrawler"), "freecrawler", "Canis Freecrawler", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("hellion"), "hellion", "Annis Hellion", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("insurgent"), "insurgent", "HVY Insurgent Pick-up", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("insurgent2"), "insurgent2", "HVY Insurgent", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("insurgent3"), "insurgent3", "HVY Insurgent Pick-up Custom", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("kalahari"), "kalahari", "Canis Kalahari", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("mesa3"), "mesa3", "Canis Mesa (Merryweather)", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("monster"), "monster", "Vapid Liberator", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("monster3"), "monster3", "Vapid Liberator", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("monster4"), "monster4", "Vapid Liberator", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("monster5"), "monster5", "Vapid Liberator", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("menacer"), "menacer", "HVY Menacer", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("nightshark"), "nightshark", "HVY Nightshark", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rancherxl"), "rancherxl", "Declasse Rancher XL", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rancherxl2"), "rancherxl2", "Declasse Rancher XL", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rebel"), "rebel", "Karin Rebel", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rebel2"), "rebel2", "Karin Rebel", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rcbandito"), "rcbandito", "RC Bandito", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("riata"), "riata", "Vapid Riata", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sandking"), "sandking", "Vapid Sandking XL", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sandking2"), "sandking2", "Vapid Sandking SWB", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("technical"), "technical", "Karin Technical", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("technical2"), "technical2", "Karin Technical", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("technical3"), "technical3", "Karin Technical", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("trophytruck"), "trophytruck", "Vapid Trophy Truck", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("trophytruck2"), "trophytruck2", "Vapid Trophy Truck", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("yosemite3"), "yosemite3", "Declasse Yosemite Rancher", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("winky"), "winky", "Vapid Winky", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("verus"), "verus", "Dinka Verus", VEHICLE_CLASS_OFFROAD, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bulldozer"), "bulldozer", "HVY Dozer", VEHICLE_CLASS_INDUSTRIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cutter"), "cutter", "HVY Cutter", VEHICLE_CLASS_INDUSTRIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dump"), "dump", "HVY Dump", VEHICLE_CLASS_INDUSTRIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("flatbed"), "flatbed", "MTL Flatbed", VEHICLE_CLASS_INDUSTRIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("guardian"), "guardian", "Vapid Guardian", VEHICLE_CLASS_INDUSTRIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("handler"), "handler", "HVY Dock Handler", VEHICLE_CLASS_INDUSTRIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("mixer"), "mixer", "HVY Mixer", VEHICLE_CLASS_INDUSTRIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("mixer2"), "mixer2", "HVY Mixer II", VEHICLE_CLASS_INDUSTRIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rubble"), "rubble", "Jobuilt Rubble", VEHICLE_CLASS_INDUSTRIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tiptruck2"), "tiptruck2", "Brute Tipper II", VEHICLE_CLASS_INDUSTRIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("airtug"), "airtug", "HVY Airtug", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("caddy"), "caddy", "Nagasaki Caddy", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("caddy2"), "caddy2", "Nagasaki Caddy (Bunker)", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("caddy3"), "caddy3", "Nagasaki Caddy (Utility)", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("docktug"), "docktug", "HVY Docktug", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("forklift"), "forklift", "HVY Forklift", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("mower"), "mower", "Jacksheepe Lawn Mower", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ripley"), "ripley", "HVY Ripley", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sadler"), "sadler", "Vapid Sadler", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sadler2"), "sadler2", "Vapid Sadler", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("scrap"), "scrap", "Vapid Scrap Truck", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("towtruck"), "towtruck", "Vapid Tow Truck", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("towtruck2"), "towtruck2", "Vapid Tow Truck (Large)", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tractor"), "tractor", "Stanley Tractor", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tractor2"), "tractor2", "Stanley Tractor", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tractor3"), "tractor3", "Stanley Tractor", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("utillitruck"), "utillitruck", "Brute Utility Truck", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("utillitruck2"), "utillitruck2", "Brute Utility Truck (Cherry Picker)", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("utillitruck3"), "utillitruck3", "Vapid Utility Truck (Contender)", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("slamtruck"), "slamtruck", "Slamtruck", VEHICLE_CLASS_UTILITY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bison"), "bison", "Bravado Bison", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bison2"), "bison2", "Bravado Bison", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bison3"), "bison3", "Bravado Bison", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bobcatxl"), "bobcatxl", "Vapid Bobcat XL", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("boxville"), "boxville", "Brute Boxville", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("boxville2"), "boxville2", "Brute Boxville", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("boxville3"), "boxville3", "Brute Boxville", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("boxville4"), "boxville4", "Brute Boxville", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("boxville5"), "boxville5", "Brute Boxville (Armored)", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("burrito"), "burrito", "Declasse Burrito", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("burrito2"), "burrito2", "Declasse Burrito", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("burrito3"), "burrito3", "Declasse Burrito", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("burrito4"), "burrito4", "Declasse Burrito", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("burrito5"), "burrito5", "Declasse Burrito", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("camper"), "camper", "Brute Camper", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("gburrito"), "gburrito", "Declasse Gang Burrito", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("gburrito2"), "gburrito2", "Declasse Gang Burrito", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("journey"), "journey", "Zirconium Journey", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("minivan"), "minivan", "Vapid Minivan", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("minivan2"), "minivan2", "Vapid Minivan Custom", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("paradise"), "paradise", "Bravado Paradise", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("pony"), "pony", "Brute Pony", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("pony2"), "pony2", "Brute Pony", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rumpo"), "rumpo", "Bravado Rumpo", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rumpo2"), "rumpo2", "Bravado Rumpo", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rumpo3"), "rumpo3", "Bravado Rumpo Custom", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("speedo"), "speedo", "Vapid Speedo", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("speedo2"), "speedo2", "Vapid Speedo", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("speedo4"), "speedo4", "Vapid Speedo Custom", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("surfer"), "surfer", "BF Surfer", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("surfer2"), "surfer2", "BF Surfer", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("taco"), "taco", "Brute Taco Van", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("youga"), "youga", "Bravado Youga", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("youga2"), "youga2", "Bravado Youga Classic", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("youga3"), "youga3", "Bravado Youga Classic 4x4", VEHICLE_CLASS_VAN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bmx"), "bmx", "BMX", VEHICLE_CLASS_CYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cruiser"), "cruiser", "Cruiser", VEHICLE_CLASS_CYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("fixter"), "fixter", "Fixter", VEHICLE_CLASS_CYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("scorcher"), "scorcher", "Scorcher", VEHICLE_CLASS_CYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tribike"), "tribike", "Endurex Race Bike", VEHICLE_CLASS_CYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tribike2"), "tribike2", "Tri-Cycles Race Bike", VEHICLE_CLASS_CYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tribike3"), "tribike3", "Whippet Race Bike", VEHICLE_CLASS_CYCLE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dinghy4"), "dinghy4", "Nagasaki Dinghy", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("jetmax"), "jetmax", "Shitzu Jetmax", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("seashark"), "seashark", "Speedophile Seashark", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("seashark2"), "seashark2", "Speedophile Seashark Lifeguard", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("seashark3"), "seashark3", "Speedophile Seashark", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("speeder"), "speeder", "Pegassi Speeder", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("speeder2"), "speeder2", "Pegassi Speeder", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("squalo"), "squalo", "Shitzu Squalo", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("submersible"), "submersible", "Submersible", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("submersible2"), "submersible2", "Kraken Submersible", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("suntrap"), "suntrap", "Shitzu Suntrap", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("toro"), "toro", "Lampadati Toro", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("toro2"), "toro2", "Lampadati Toro", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tropic"), "tropic", "Shitzu Tropic", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tropic2"), "tropic2", "Shitzu Tropic", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tug"), "tug", "Buckingham Tug", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("avisa"), "avisa", "Kraken Submersibles Avisa", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dinghy5"), "dinghy5", "Nagasaki Weaponized Dinghy", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("patrolboat"), "patrolboat", "Kurtz 31 Patrol Boat", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("longfin"), "longfin", "Shitzu Longfin", VEHICLE_CLASS_BOAT, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("akula"), "akula", "Akula", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("annihilator"), "annihilator", "Western Company Annihilator", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("buzzard"), "buzzard", "Nagasaki Buzzard", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("buzzard2"), "buzzard2", "Nagasaki Buzzard Attack Chopper", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cargobob"), "cargobob", "Western Company Cargobob", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cargobob2"), "cargobob2", "Western Company Cargobob Jetsam", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cargobob3"), "cargobob3", "Western Company Cargobob", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cargobob4"), "cargobob4", "Western Company Cargobob", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("frogger"), "frogger", "Maibatsu Frogger", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("frogger2"), "frogger2", "Maibatsu Frogger", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("havok"), "havok", "Nagasaki Havok", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("hunter"), "hunter", "FH-1 Hunter", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("maverick"), "maverick", "Buckingham Maverick", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("savage"), "savage", "Savage", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("seasparrow"), "seasparrow", "Sea Sparrow", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("skylift"), "skylift", "HVY Skylift", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("supervolito"), "supervolito", "Buckingham SuperVolito", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("supervolito2"), "supervolito2", "Buckingham SuperVolito Carbon", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("swift"), "swift", "Buckingham Swift", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("swift2"), "swift2", "Buckingham Swift Deluxe", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("valkyrie"), "valkyrie", "Buckingham Valkyrie", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("valkyrie2"), "valkyrie2", "Buckingham Valkyrie", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("volatus"), "volatus", "Buckingham Volatus", VEHICLE_CLASS_HELICOPTER, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("alphaz1"), "alphaz1", "Buckingham Alpha-Z1", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("avenger"), "avenger", "Mammoth Avenger", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("besra"), "besra", "Western Company Besra", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("blimp"), "blimp", "Atomic Blimp", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("blimp2"), "blimp2", "Xero Blimp", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("blimp3"), "blimp3", "Blimp", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bombushka"), "bombushka", "RM-10 Bombushka", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cargoplane"), "cargoplane", "Cargo Plane", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cuban800"), "cuban800", "Western Company Cuban 800", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("dodo"), "dodo", "Mammoth Dodo", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("duster"), "duster", "Western Company Duster", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("howard"), "howard", "Buckingham Howard NX-25", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("hydra"), "hydra", "Mammoth Hydra", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("jet"), "jet", "Jet", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("lazer"), "lazer", "Jobuilt P-996 Lazer", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("luxor"), "luxor", "Buckingham Luxor", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("luxor2"), "luxor2", "Buckingham Luxor", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("mammatus"), "mammatus", "Jobuilt Mammatus", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("microlight"), "microlight", "Pegassi Ultralight", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("miljet"), "miljet", "Buckingham Miljet", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("mogul"), "mogul", "Mammoth Mogul", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("molotok"), "molotok", "V-65 Molotok", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("nimbus"), "nimbus", "Buckingham Nimbus", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("nokota"), "nokota", "P-45 Nokota", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("pyro"), "pyro", "Buckingham Pyro", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rogue"), "rogue", "Western Company Rogue", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("seabreeze"), "seabreeze", "Western Company Seabreeze", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("shamal"), "shamal", "Buckingham Shamal", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("starling"), "starling", "LF-22 Starling", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("strikeforce"), "strikeforce", "B-11 Strikeforce", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("stunt"), "stunt", "Western Company Mallard", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("titan"), "titan", "Titan", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tula"), "tula", "Mammoth Tula", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("velum"), "velum", "Jobuilt Velum", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("velum2"), "velum2", "Jobuilt Velum 5-Seater", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("vestra"), "vestra", "Buckingham Vestra", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("volatol"), "volatol", "Volatol", VEHICLE_CLASS_PLANE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("airbus"), "airbus", "Brute Airport Bus", VEHICLE_CLASS_SERVICE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("brickade"), "brickade", "MTL Brickade", VEHICLE_CLASS_SERVICE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("bus"), "bus", "Brute Bus", VEHICLE_CLASS_SERVICE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("coach"), "coach", "Brute Dashound", VEHICLE_CLASS_SERVICE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("pbus2"), "pbus2", "Festival Bus", VEHICLE_CLASS_SERVICE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rallytruck"), "rallytruck", "MTL Dune", VEHICLE_CLASS_SERVICE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rentalbus"), "rentalbus", "Brute Rental Shuttle Bus", VEHICLE_CLASS_SERVICE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("taxi"), "taxi", "Vapid Taxi", VEHICLE_CLASS_SERVICE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tourbus"), "tourbus", "Brute Tour Bus", VEHICLE_CLASS_SERVICE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("trash"), "trash", "Jobuilt Trashmaster", VEHICLE_CLASS_SERVICE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("trash2"), "trash2", "Jobuilt Trashmaster", VEHICLE_CLASS_SERVICE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("wastelander"), "wastelander", "MTL Wastelander", VEHICLE_CLASS_SERVICE, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("ambulance"), "ambulance", "Brute Ambulance", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("fbi"), "fbi", "Bravado FIB (Buffalo)", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("fbi2"), "fbi2", "Declasse FIB (SUV)", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("lguard"), "lguard", "Declasse Lifeguard", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("pbus"), "pbus", "Vapid Police Prison Bus", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("police"), "police", "Vapid Police Cruiser", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("police2"), "police2", "Bravado Police Cruiser (Buffalo)", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("police3"), "police3", "Vapid Police Cruiser (Interceptor)", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("police4"), "police4", "Vapid Unmarked Cruiser", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("policeb"), "policeb", "Western Police Bike", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("polmav"), "polmav", "Buckingham Police Maverick", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("pranger"), "pranger", "Declasse Park Ranger", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("predator"), "predator", "Police Predator", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("riot"), "riot", "Brute Police Riot", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("riot2"), "riot2", "RCV", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sheriff"), "sheriff", "Vapid Sheriff Cruiser", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("sheriff2"), "sheriff2", "Declasse Sheriff SUV", VEHICLE_CLASS_EMERGENCY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("apc"), "apc", "HVY APC tank", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("barracks"), "barracks", "HVY Barracks", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("barracks2"), "barracks2", "HVY Barracks Semi", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("barracks3"), "barracks3", "HVY Barracks", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("barrage"), "barrage", "Barrage", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("chernobog"), "chernobog", "HVY Chernobog", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("crusader"), "crusader", "Canis Crusader", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("halftrack"), "halftrack", "Bravado Half-track", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("khanjali"), "khanjali", "TM-02 Khanjali Tank", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("rhino"), "rhino", "Rhino Tank", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("scarab"), "scarab", "HVY Scarab (Arena)", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("scarab2"), "scarab2", "HVY Scarab (Arena)", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("scarab3"), "scarab3", "HVY Scarab (Arena)", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("thruster"), "thruster", "Mammoth Thruster Jetpack", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("trailersmall2"), "trailersmall2", "Vom Feurer Anti-Aircraft Trailer", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("vetir"), "vetir", "Vetir", VEHICLE_CLASS_MILITARY, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("benson"), "benson", "Vapid Benson", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("biff"), "biff", "HVY Biff", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cerberus"), "cerberus", "MTL Cerberus (Arena)", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cerberus2"), "cerberus2", "MTL Cerberus (Arena)", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cerberus3"), "cerberus3", "MTL Cerberus (Arena)", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("hauler"), "hauler", "Jobuilt Hauler", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("hauler2"), "hauler2", "Jobuilt Hauler Custom", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("mule"), "mule", "Maibatsu Mule", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("mule2"), "mule2", "Maibatsu Mule (Armored)", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("mule3"), "mule3", "Maibatsu Mule Custom", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("mule4"), "mule4", "Maibatsu Mule", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("packer"), "packer", "MTL Packer", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("phantom"), "phantom", "Jobuilt Phantom", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("phantom2"), "phantom2", "Jobuilt Phantom Custom", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("phantom3"), "phantom3", "Jobuilt Phantom Wedge", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("pounder"), "pounder", "MTL Pounder", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("pounder2"), "pounder2", "MTL Pounder Custom", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("stockade"), "stockade", "Brute Stockade", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("stockade3"), "stockade3", "Brute Stockade", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("terbyte"), "terbyte", "Benefactor Terrorbyte", VEHICLE_CLASS_COMMERCIAL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("cablecar"), "cablecar", "Cable Car", VEHICLE_CLASS_TRAIN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("freight"), "freight", "Freight", VEHICLE_CLASS_TRAIN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("freightcar"), "freightcar", "Freight Car", VEHICLE_CLASS_TRAIN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("freightcont1"), "freightcont1", "Freight Container 1", VEHICLE_CLASS_TRAIN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("freightcont2"), "freightcont2", "Freight Container 2", VEHICLE_CLASS_TRAIN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("freightgrain"), "freightgrain", "Freight Grain", VEHICLE_CLASS_TRAIN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("metrotrain"), "metrotrain", "Metro Train", VEHICLE_CLASS_TRAIN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("tankercar"), "tankercar", "Tanker Car", VEHICLE_CLASS_TRAIN, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("openwheel2"), "openwheel2", "Declasse DR1 (IndyCar)", VEHICLE_CLASS_OPEN_WHEEL, VEHICLE_DLC_NONE },
			{ RAGE_JOAAT_IMPL("openwheel1"), "openwheel1", "Benefactor BR8 (Formula 1 Car)", VEHICLE_CLASS_OPEN_WHEEL, VEHICLE_DLC_NONE }
		};
	}
}
#pragma warning(pop)